#name=input("what is your name")
#print("my name is",terry)
f_name=input("what is your first name:")
s_name=input("what is your second name:")
print("my name is:",f_name)
print("my second name:",s_name)
f_num=input("enter first number:")
s_num=input("enter second number:")
#convert the string to integers
sum_num=int(f_num)+int(s_num)
print("The sum of the number is:",sum_num)
diff_num=int(f_num)
print("The difference of the number is:")
quot_num=int(f_num)/(s_num)
print("The quotient of the number is:",sum_num)
